### ISSUE TITLE
setting style when using the fastest method.

### ISSUE THREAD

**Issue by amp79** [kz26/PyExcelerate#90]
when using wb.new_sheet("some-sheet", data=data)  method. is there any way i can set styles too?

**Comment by kevmo314** [comment]
Directly calling the styling api will be the most performant, adding a bulk import method won't be any faster unfortunately due to the way the internals are set up. If anything, it'll actually be slower.

Additionally, styling is quite expensive so we don't really want to encourage them with the goal of performance.

**Comment by amp79** [comment]
thanks i understand.
