### ISSUE TITLE
Does Excel support Multiprocessing?

### ISSUE THREAD

**Issue by KentonParton** [kz26/PyExcelerate#98]
This is an open question. Is it possible to write to a single Excel File sheet in parallel using Multiprocessing? PyExcelerate doesn't support this but could this even be done?

**Comment by kevmo314** [comment]
No, I looked into this a while ago. Even for very large files, multiprocessing didn't bring any significant gains. Because the Excel file has to be built up and it's one single file, it becomes basically a lock and multiple processes end up just locking on the writing of the file.

If you or anyone happens to find otherwise I'd be happy to incorporate multiprocessing into the library, but my own investigation didn't yield much improvement.

**Comment by KentonParton** [comment]
@kevmo314 I experienced the same thing. Thanks for the feedback.
